name: Go tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '^1.18.0-beta1'
      - name: Run tests
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - uses: codecov/codecov-action@v2
        with:
          #files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: go generics util library
          verbose: true